# Generated by Django 5.1.5 on 2026-04-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('max_health', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=100)),
                ('max_mana', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('adventure', models.CharField(blank=True, max_length=100, null=True)),
                ('stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
