version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Używamy Dockerfile w trybie produkcji (zbudowana aplikacja)
    ports:
      - "80:80"  # Serwowanie aplikacji na porcie 80
    environment:
      - REACT_APP_API_URL=http://backend:8000  # Backend API URL
    depends_on:
      - backend
    networks:
      - rpg_network
    restart: always  # Aplikacja będzie zawsze restartować się po awarii

  backend:
    build:
      context: ./backend
    env_file:
      - .env  # Załaduj plik .env
    ports:
      - "8000:8000"  # Serwowanie backendu na porcie 8000
    volumes:
      - ./backend:/app
      - ./backend/wait-for-it.sh:/app/wait-for-it.sh
    depends_on:
      - db
      - redis
    command: bash -c "./wait-for-it.sh db:5432 -- python manage.py migrate --noinput && daphne -b 0.0.0.0 -p 8000 rpg_project.asgi:application"
    networks:
      - rpg_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    restart: always  # Backend będzie restartować się w razie awarii

  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    hostname: db
    networks:
      - rpg_network
    ports:
      - "5432:5432"  # Udostępnienie bazy danych na porcie 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "django_rpg", "-h", "db", "-p", "5432"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    restart: always  # Restart bazy danych w przypadku awarii

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"  # Redis na porcie 6379
    networks:
      - rpg_network
    env_file:
      - .env
    restart: always  # Restart Redis w razie awarii

networks:
  rpg_network:
    driver: bridge

volumes:
  db_data:  # Dzięki temu dane bazy danych są przechowywane na zewnątrz kontenera
