# Generated by Django 5.1.5 on 2025-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='scenario',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
