# Generated by Django 5.1.5 on 2025-03-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_location_adventure'),
        ('chat', '0002_room_scenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='scenario',
        ),
        migrations.AddField(
            model_name='room',
            name='adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.adventure'),
        ),
    ]
