# Generated by Django 5.1.5 on 2026-04-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('story', 'Story'), ('choice', 'Choice'), ('combat', 'Combat'), ('item', 'Item'), ('status', 'Status'), ('quest', 'Quest'), ('shop', 'Shop'), ('treasure', 'Treasure')], default='story', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('required_flags', models.JSONField(blank=True, default=list)),
                ('blocking_flags', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('consequences', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
