# Generated by Django 5.1.5 on 2025-03-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('story', 'Historia'), ('choice', 'Wybór'), ('combat', 'Walka'), ('item', 'Przedmiot'), ('status', 'Status'), ('quest', 'Zadanie'), ('shop', 'Sklep'), ('treasure', 'Skarb')], default='story', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('required_flags', models.JSONField(blank=True, default=list)),
                ('blocking_flags', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('consequences', models.JSONField(blank=True, default=dict)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='adventures.adventure')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_events', to='adventures.location')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='characters.playercharacter')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='characters.playercharacter')),
            ],
        ),
    ]
