# Generated by Django 5.1.5 on 2025-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevent',
            name='event_type',
            field=models.CharField(choices=[('story', 'Story'), ('choice', 'Choice'), ('combat', 'Combat'), ('item', 'Item'), ('status', 'Status'), ('quest', 'Quest'), ('shop', 'Shop'), ('treasure', 'Treasure')], default='story', max_length=20),
        ),
    ]
