# Generated by Django 5.1.5 on 2026-04-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_initial'),
        ('game', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='world.adventure'),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_events', to='world.location'),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='characters.playercharacter'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='characters.playercharacter'),
        ),
    ]
