# Generated by Django 5.1.5 on 2025-03-03 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
