# Generated by Django 5.1.5 on 2025-02-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': 'choices'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order'], 'verbose_name_plural': 'locations'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='adventure',
        ),
        migrations.AddField(
            model_name='adventure',
            name='locations',
            field=models.ManyToManyField(related_name='adventures', to='adventures.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='adventures.location', verbose_name='Current location'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='next_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_leading_here', to='adventures.location', verbose_name='Next location'),
        ),
    ]
