# Generated by Django 5.1.5 on 2025-02-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_alter_choice_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='adventures', to='adventures.location'),
        ),
    ]
