# Generated by Django 5.1.5 on 2025-02-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_alter_adventure_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.adventure'),
        ),
    ]
